VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ## ###########################################################################  
  ## VM
  ## ###########################################################################  

  config.vm.box = "ubuntu/trusty64"

  ## ###########################################################################  
  ## PROVISIONING
  ## ###########################################################################  

  ## Basic system dependencies
  config.vm.provision :shell, :path => "bootstrap.sh"
  
  ## Git
  config.vm.provision :shell, :path => "bootstrap-git.sh"
  
  ## Java (7 or 8, check script)
  config.vm.provision :shell, :path => "bootstrap-java.sh"
  
  ## Maven
  config.vm.provision :shell, :path => "bootstrap-maven.sh"
  
  ## Jenkins
  config.vm.provision :shell, :path => "bootstrap-jenkins.sh"
  
  ## ###########################################################################  
  ## PORT FORWARDING
  ## ###########################################################################  

  ## Jenkins forwarding
  config.vm.network :forwarded_port, host: 8081, guest: 8080
  
  ## ###########################################################################  
  ## VM HARDWARE SETTINGS
  ## ###########################################################################  

  config.vm.provider "virtualbox" do |v|
    v.name = "jenkins"
    v.memory = 512
    v.cpus = 1
    v.gui = false
  end
end

